'use client';

import { useState } from 'react';
import Link from 'next/link';
import InfoHeader from '@/app/info/[slug]/InfoHeader';
import {
  ArrowLeft, ShieldCheck, AlertTriangle, Globe,
  ChevronDown, ChevronUp, Lock, Eye, Database,
  Users, Bell, Scale, HelpCircle,
  Mail, Cookie, Trash2, UserCheck,
  AlertCircle, Fingerprint
} from 'lucide-react';

// ─── Types ────────────────────────────────────────────────────────────────────
type Lang = 'en' | 'bn';

// ─── Section Accordion ───────────────────────────────────────────────────────
function SectionBlock({ title, children, icon: Icon, accent = 'blue' }: {
  title: string;
  children: React.ReactNode;
  icon?: any;
  accent?: string;
}) {
  const [open, setOpen] = useState(true);
  const accentMap: Record<string, string> = {
    blue:   'bg-blue-50 dark:bg-blue-900/20 text-blue-600',
    green:  'bg-green-50 dark:bg-green-900/20 text-green-600',
    red:    'bg-red-50 dark:bg-red-900/20 text-red-600',
    amber:  'bg-amber-50 dark:bg-amber-900/20 text-amber-600',
    purple: 'bg-purple-50 dark:bg-purple-900/20 text-purple-600',
    orange: 'bg-orange-50 dark:bg-orange-900/20 text-orange-600',
  };
  return (
    <div className="border border-slate-200 dark:border-slate-800 rounded-2xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-3 p-5 text-left bg-slate-50 dark:bg-slate-800/40 hover:bg-slate-100 dark:hover:bg-slate-800/70 transition-colors"
      >
        <div className="flex items-center gap-3">
          {Icon && (
            <div className={`p-2 rounded-xl ${accentMap[accent] ?? accentMap['blue']}`}>
              <Icon size={18} />
            </div>
          )}
          <span className="font-black text-slate-800 dark:text-slate-100 uppercase tracking-tight text-sm md:text-base">{title}</span>
        </div>
        {open ? <ChevronUp size={18} className="text-slate-400 shrink-0" /> : <ChevronDown size={18} className="text-slate-400 shrink-0" />}
      </button>
      {open && <div className="p-5 md:p-6 space-y-3 text-slate-600 dark:text-slate-400 text-sm md:text-base leading-relaxed">{children}</div>}
    </div>
  );
}

function InfoBox({ type, children }: { type: 'warning' | 'info' | 'danger' | 'success'; children: React.ReactNode }) {
  const styles = {
    warning: 'bg-amber-50 dark:bg-amber-900/10 border-amber-200 dark:border-amber-900/30 text-amber-700 dark:text-amber-400',
    info:    'bg-blue-50 dark:bg-blue-900/10 border-blue-200 dark:border-blue-900/30 text-blue-700 dark:text-blue-300',
    danger:  'bg-red-50 dark:bg-red-900/10 border-red-200 dark:border-red-900/30 text-red-700 dark:text-red-400',
    success: 'bg-green-50 dark:bg-green-900/10 border-green-200 dark:border-green-900/30 text-green-700 dark:text-green-400',
  };
  const icons = { warning: AlertTriangle, info: AlertCircle, danger: AlertTriangle, success: ShieldCheck };
  const Icon = icons[type];
  return (
    <div className={`flex gap-3 items-start p-4 rounded-xl border font-semibold text-sm ${styles[type]}`}>
      <Icon size={18} className="shrink-0 mt-0.5" />
      <div>{children}</div>
    </div>
  );
}

// ─── ENGLISH PRIVACY CONTENT ─────────────────────────────────────────────────
function EnglishContent() {
  return (
    <div className="space-y-4">
      <p className="text-slate-600 dark:text-slate-400 text-sm md:text-base leading-relaxed font-medium">
        Xelpay (Xenverse IT) is committed to protecting your privacy and handling your personal data with full transparency, in compliance with the <strong className="text-slate-900 dark:text-white">Digital Security Act, 2018 (Bangladesh)</strong>, the Information and Communication Technology Act, 2006 (Bangladesh), Bangladesh Bank data protection guidelines, GDPR principles (for EU users), and general international best practices. This Privacy Policy explains exactly what data we collect, why we collect it, and how it is used, stored, and protected.
      </p>

      <SectionBlock title="1. Comprehensive Information We Collect" icon={Database} accent="green">
        <p className="font-semibold text-slate-700 dark:text-slate-300">We collect structured data across the following categories:</p>
        <ul className="list-disc pl-5 mt-3 space-y-3">
          <li><strong className="text-slate-800 dark:text-slate-200">Merchant Identification Data:</strong> Full legal name, verified email address, mobile phone number, business name, and geographic location — provided during account registration and onboarding.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Technical Integration Data:</strong> API keys generated by our system, Webhook endpoint URLs you configure, Custom Telegram Bot Tokens, associated Telegram Chat IDs, and IMAP email credentials stored in an encrypted vault.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Transaction & Payment Metadata:</strong> To verify and approve payment orders, our automated systems process and log Transaction IDs (TrxID), exact transaction amounts, timestamps, MFS sender phone numbers, payment method types, and order reference numbers.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Device & App Metadata (Relay Apps):</strong> If you use our Android Relay or SMS Reader application, we explicitly collect and store device-specific operational information, including: Device Model, Android OS Version, App Version, Connectivity Status (online/offline), and last-seen timestamp. This data is strictly required to maintain synchronization reliability, monitor device health, and ensure payment verification continuity.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Add-On Usage Data:</strong> Where the Merchant has activated any Add-On service (as described in the Terms of Service, Section 5), we collect and retain usage metrics relating to such Add-On consumption — including, but not limited to, the number of outbound notification emails dispatched, the number of premium SMS alerts sent, timestamps, and recipient metadata — for the purposes of accurate usage-based billing, invoice generation, and dispute resolution.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">KYC & Business Verification Documents:</strong> Where required under our KYC and Business Verification policy (Terms of Service, Section 15), we collect, process, and securely store business identity documents submitted by the Merchant, including but not limited to Trade Licenses, National Identity Card (NID) copies, and TIN Certificates. These documents are processed exclusively for compliance, AML, and regulatory purposes and are handled in strict accordance with applicable data protection laws.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Usage & Log Data:</strong> IP addresses, browser type, operating system, pages visited within the dashboard, feature interactions, and session timestamps — collected automatically for security monitoring, fraud detection, and system improvement.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Communications:</strong> Records of support conversations, feedback messages, and email correspondence between you and Xelpay support staff.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Affiliate & Referral Data:</strong> Referral link clicks, referred account details, and commission calculation data for participants in the Xelpay Affiliate Program.</li>
        </ul>
        <div className="mt-4">
          <InfoBox type="success">
            <strong className="block mb-1">What We NEVER Collect:</strong>
            Under absolutely no circumstances does Xelpay record, store, log, or intercept your: Bank Account Passwords, MFS App PIN Codes (bKash PIN, Nagad PIN, etc.), OTPs (One Time Passwords), NID/Passport Numbers (except when voluntarily submitted for KYC compliance as described above), raw Credit/Debit Card numbers, or CVV codes. Our SMS and email reading is exclusively limited to post-transaction notification parsing — we do not read personal, private, or non-payment-related communications.
          </InfoBox>
        </div>
      </SectionBlock>

      <SectionBlock title="2. Legal Basis for Processing Personal Data" icon={Scale} accent="green">
        <p>Xelpay processes your personal data under one or more of the following legal bases:</p>
        <ul className="list-disc pl-5 mt-3 space-y-2">
          <li><strong className="text-slate-800 dark:text-slate-200">Contractual Necessity:</strong> Processing is required to fulfil our service agreement with you (delivering payment automation, API access, and related features).</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Legitimate Interests:</strong> Fraud prevention, security monitoring, platform abuse detection, and continuous service improvement — balanced against your rights.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Legal Obligation:</strong> Compliance with applicable Bangladeshi law, Bangladesh Bank directives, AML regulations, BFIU KYC requirements, court orders, and regulatory requirements.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Consent:</strong> For optional features such as marketing communications, from which you may withdraw consent at any time.</li>
        </ul>
      </SectionBlock>

      <SectionBlock title="3. Purpose of Data Utilization" icon={Eye} accent="green">
        <p>Your data is used strictly for the following operational purposes:</p>
        <ul className="list-disc pl-5 mt-3 space-y-2">
          <li>To reliably authenticate users and maintain robust workspace security and session integrity.</li>
          <li>To algorithmically verify incoming payments and fire real-time Webhook payloads to your configured server endpoints.</li>
          <li>To dispatch instant payment success/failure alerts via Telegram to your connected personal DM or Team Group.</li>
          <li>To identify transaction anomalies, proactively prevent platform abuse, spam, and financial fraud.</li>
          <li>To generate analytics, reports, and dashboard metrics for your own business performance review.</li>
          <li>To calculate, invoice, and collect usage-based fees for any activated Add-On services.</li>
          <li>To process, review, and retain KYC and Business Verification documentation in compliance with AML and BFIU regulatory obligations.</li>
          <li>To send transactional system emails, security alerts, and billing notices.</li>
          <li>To fulfill our legal obligations under AML and fraud prevention regulations.</li>
          <li>To improve our platform's features, fix bugs, and optimize system performance based on anonymized usage patterns.</li>
        </ul>
        <InfoBox type="info">
          Xelpay does <strong>NOT</strong> use your data for third-party advertising, profiling, or sale to data brokers. Your data is never used to target you with ads on other platforms.
        </InfoBox>
      </SectionBlock>

      <SectionBlock title="4. Cookies & Tracking Technologies" icon={Cookie} accent="green">
        <p>Xelpay uses the following technologies on our platform:</p>
        <ul className="list-disc pl-5 mt-3 space-y-2">
          <li><strong className="text-slate-800 dark:text-slate-200">Essential Session Cookies:</strong> Required to maintain your secure authenticated login state. These cannot be disabled without breaking platform functionality.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Preference Storage (Local Storage):</strong> We use browser local storage to remember your UI preferences, such as Dark/Light Mode selection, language preference, and dashboard layout settings.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Security Tokens:</strong> CSRF protection tokens and similar security mechanisms to protect your account from cross-site attacks.</li>
        </ul>
        <p className="mt-3">We do <strong>NOT</strong> deploy: third-party advertising cookies, cross-site tracking pixels, social media tracking buttons (beyond opt-in sharing features), or behavioral profiling technologies. You can clear cookies and local storage via your browser settings, which will log you out of the platform.</p>
      </SectionBlock>

      <SectionBlock title="5. Third-Party Data Sharing & Disclosure" icon={Users} accent="green">
        <p><strong className="text-slate-800 dark:text-slate-200">Xelpay does NOT monetize, sell, rent, or arbitrarily share your personal data.</strong> Data is only disclosed under the following strictly defined circumstances:</p>
        <ul className="list-disc pl-5 mt-3 space-y-3">
          <li><strong className="text-slate-800 dark:text-slate-200">Infrastructure Providers:</strong> We share encrypted, minimal operational data with our trusted, industry-leading infrastructure partners — such as Vercel (hosting), Supabase (database), and equivalent providers — strictly necessary to host, operate, and maintain the software. These partners are contractually bound to data confidentiality.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Legal & Regulatory Disclosure:</strong> If served with a legally valid subpoena, court order, or formal request from cybercrime investigation units, the Bangladesh Financial Intelligence Unit (BFIU), Bangladesh Bank, law enforcement agencies, or any competent regulatory authority — we will fully cooperate and release the minimum legally required merchant data, logs, and transaction records.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Fraud Prevention:</strong> In cases of suspected fraud, money laundering, or serious criminal activity detected on our platform, Xelpay may proactively share relevant account and transaction data with BFIU, law enforcement, or relevant MFS providers without prior notice.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Business Transfer:</strong> In the event of a merger, acquisition, asset sale, or corporate restructuring of Xenverse IT, your data may be transferred to the acquiring entity, subject to the same privacy protections. You will be notified in advance where legally required.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">With Your Explicit Consent:</strong> In any other circumstance not listed above, data will only be shared with your express written consent.</li>
        </ul>
      </SectionBlock>

      <SectionBlock title="6. Data Security & Breach Notification Protocol" icon={Lock} accent="green">
        <p>Xelpay deploys multiple layers of security to protect your information:</p>
        <ul className="list-disc pl-5 mt-3 space-y-2">
          <li><strong className="text-slate-800 dark:text-slate-200">Encryption at Rest:</strong> Sensitive configuration strings — including Bot Tokens, IMAP credentials, and API configurations — are encrypted within our databases using industry-standard AES-256 encryption.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Encryption in Transit:</strong> All communication between your systems and Xelpay is exclusively enforced over HTTPS/TLS 1.2+ protocols. Plain HTTP connections are rejected.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Access Controls:</strong> Internal access to merchant data is restricted on a strict need-to-know basis. Administrative access requires multi-factor authentication.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Security Monitoring:</strong> Xelpay employs automated anomaly detection, rate limiting, and intrusion detection systems to monitor for unauthorized access attempts.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Breach Notification:</strong> In the event of a confirmed data breach that exposes your personal or API data, Xelpay commits to notifying affected merchants within <strong>72 hours</strong> of internal verification, in accordance with international best practices. The notification will describe the nature of the breach, data affected, and mitigation steps taken.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Limitation:</strong> No security system is completely impenetrable. While we implement industry-standard protections, Xelpay cannot guarantee absolute security against all possible threats. You use the platform acknowledging this inherent risk.</li>
        </ul>
      </SectionBlock>

      <SectionBlock title="7. Consent to Electronic Communications" icon={Bell} accent="green">
        <p>By registering a Xelpay account, you explicitly and freely consent to receive the following types of electronic communications from us:</p>
        <ul className="list-disc pl-5 mt-3 space-y-2">
          <li><strong className="text-slate-800 dark:text-slate-200">Transactional & Operational:</strong> Account creation confirmations, payment verification alerts, API error notifications, security warnings, Telegram bot activity reports, and billing/invoice emails. These are mandatory and cannot be opted out of while the account is active, as they are essential to service delivery.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">System Updates & Policy Changes:</strong> Platform update announcements, maintenance notices, and policy change notifications.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Promotional & Marketing:</strong> News about new features, special offers, and platform upgrades. You may opt out of marketing communications at any time by clicking the unsubscribe link in any such email or by contacting our support.</li>
        </ul>
      </SectionBlock>

      <SectionBlock title="8. Data Retention Policy" icon={Database} accent="green">
        <ul className="list-disc pl-5 space-y-3">
          <li><strong className="text-slate-800 dark:text-slate-200">Active Account Data:</strong> Your merchant profile, gateway configurations, and transaction logs are retained for as long as your account is active and for a reasonable period thereafter to enable potential account reactivation.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">KYC & Business Verification Documents:</strong> KYC documents submitted pursuant to the Terms of Service, Section 15 are retained for the duration of the account relationship and, upon termination, for the mandatory minimum period required by BFIU and AML regulations, which shall be no less than Five (5) years following account termination, consistent with our Post-Termination AML Retention policy below.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Post-Termination AML Retention:</strong> To strictly comply with the Money Laundering Prevention Act, 2012 (Bangladesh), Bangladesh Bank AML/CFT guidelines, and applicable financial intelligence requirements, Xelpay reserves the legally mandated right to retain basic transaction logs, associated IP history, merchant identification metadata, KYC documentation, and account activity records for a minimum period of <strong className="text-slate-800 dark:text-slate-200">Five (5) years</strong> following account termination, before executing a complete data purge.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Add-On Usage Records:</strong> Detailed Add-On service usage records — required for accurate billing, invoice reconciliation, and dispute resolution — are retained for a minimum of Three (3) years following the billing period in which the usage was incurred, or for such longer period as required by applicable tax or regulatory law.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Log Data:</strong> System access logs and security logs are retained for up to 24 months for security investigation purposes, then automatically purged.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Support Communications:</strong> Support ticket records are retained for up to 3 years from the last interaction to enable historical reference and dispute resolution.</li>
        </ul>
      </SectionBlock>

      <SectionBlock title="9. Your Data Rights & Account Deletion" icon={Trash2} accent="green">
        <p>Subject to applicable law and our AML retention obligations, you possess the following rights regarding your personal data:</p>
        <ul className="list-disc pl-5 mt-3 space-y-2">
          <li><strong className="text-slate-800 dark:text-slate-200">Right of Access:</strong> You may request a copy of the personal data Xelpay holds about you.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Right to Rectification:</strong> You may update or correct inaccurate personal information through your account settings or by contacting support.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Right to Erasure ("Right to be Forgotten"):</strong> You may submit a formal account deletion request via our support channel. Upon processing, your active merchant profile and non-AML-mandated data will be permanently deleted. AML-required records will be retained as per Section 8.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Right to Data Portability:</strong> You may request your merchant data in a structured, machine-readable format.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Right to Object:</strong> You may object to certain types of data processing, including direct marketing.</li>
          <li><strong className="text-slate-800 dark:text-slate-200">Right to Withdraw Consent:</strong> Where processing is based on consent, you may withdraw it at any time, without affecting the lawfulness of prior processing.</li>
        </ul>
        <p className="mt-3">To exercise any of the above rights, contact us at our official support channel. We will respond to valid requests within 30 days.</p>
      </SectionBlock>

      <SectionBlock title="10. Children's Privacy" icon={UserCheck} accent="red">
        <InfoBox type="warning">
          Xelpay services are strictly intended for users who are 18 years of age or older. We do not knowingly collect personal data from individuals under the age of 18. If we become aware that a minor has created an account or provided us with personal information, we will immediately delete the account and all associated data. If you believe a minor has accessed our platform, please contact us immediately.
        </InfoBox>
      </SectionBlock>

      <SectionBlock title="11. International Data Transfers" icon={Globe} accent="green">
        <p>Xelpay primarily operates from Bangladesh. However, due to our use of cloud infrastructure providers such as Vercel and Supabase, your data may be stored on or transmitted through servers located outside Bangladesh, including in the United States or European Union.</p>
        <p className="mt-3">We ensure that any such international transfer of data is conducted with appropriate contractual protections in place (such as Data Processing Agreements with our providers) and only with partners who maintain data security standards equivalent to or exceeding our own.</p>
      </SectionBlock>

      <SectionBlock title="12. Contact & Data Protection Inquiries" icon={Mail} accent="green">
        <p>For all privacy-related concerns, data access requests, account deletion requests, or to report a suspected data breach, please contact us through our official support channel listed in the dashboard. We are committed to responding to all legitimate privacy inquiries within <strong className="text-slate-800 dark:text-slate-200">30 business days</strong>.</p>
        <p className="mt-3">For legal notices or regulatory correspondence, include "LEGAL / DATA PROTECTION" in your subject line to ensure proper routing to our compliance team.</p>
      </SectionBlock>
    </div>
  );
}

// ─── BANGLA PRIVACY CONTENT ───────────────────────────────────────────────────
function BanglaContent() {
  return (
    <div className="space-y-4" style={{ fontFamily: "'Noto Sans Bengali', 'SolaimanLipi', sans-serif" }}>
      <p className="text-slate-600 dark:text-slate-400 text-sm md:text-base leading-relaxed font-medium">
        Xelpay (Xenverse IT) <strong className="text-slate-900 dark:text-white">ডিজিটাল নিরাপত্তা আইন, ২০১৮ (বাংলাদেশ)</strong>, তথ্য ও যোগাযোগ প্রযুক্তি আইন, ২০০৬ (বাংলাদেশ), বাংলাদেশ ব্যাংকের ডেটা সুরক্ষা নির্দেশিকা, GDPR নীতি (EU ব্যবহারকারীদের জন্য) এবং সাধারণ আন্তর্জাতিক সর্বোত্তম অনুশীলন মেনে আপনার গোপনীয়তা রক্ষা এবং আপনার ব্যক্তিগত ডেটা সম্পূর্ণ স্বচ্ছতার সাথে পরিচালনা করতে প্রতিশ্রুতিবদ্ধ।
      </p>
      <SectionBlock title="১. আমরা কী কী তথ্য সংগ্রহ করি" icon={Database} accent="green">
        <p className="font-semibold text-slate-700 dark:text-slate-300">আমরা নিম্নলিখিত বিভাগগুলিতে কাঠামোগত ডেটা সংগ্রহ করি:</p>
        <ul className="list-disc pl-5 mt-3 space-y-3">
          <li><strong className="text-slate-800 dark:text-slate-200">মার্চেন্ট পরিচয় ডেটা:</strong> অ্যাকাউন্ট নিবন্ধন এবং অনবোর্ডিংয়ের সময় প্রদত্ত পূর্ণ আইনি নাম, যাচাইকৃত ইমেইল ঠিকানা, মোবাইল ফোন নম্বর, ব্যবসার নাম এবং ভৌগোলিক অবস্থান।</li>
          <li><strong className="text-slate-800 dark:text-slate-200">প্রযুক্তিগত ইন্টিগ্রেশন ডেটা:</strong> আমাদের সিস্টেম দ্বারা তৈরি API কী, আপনার কনফিগার করা ওয়েবহুক এন্ডপয়েন্ট URL, কাস্টম টেলিগ্রাম বট টোকেন, সংশ্লিষ্ট টেলিগ্রাম চ্যাট আইডি এবং একটি এনক্রিপ্টেড ভল্টে সংরক্ষিত IMAP ইমেইল ক্রেডেনশিয়াল।</li>
          <li><strong className="text-slate-800 dark:text-slate-200">লেনদেন ও পেমেন্ট মেটাডেটা:</strong> পেমেন্ট অর্ডার যাচাই এবং অনুমোদনের জন্য আমাদের স্বয়ংক্রিয় সিস্টেম লেনদেন আইডি (TrxID), সঠিক লেনদেনের পরিমাণ, টাইমস্ট্যাম্প, MFS প্রেরকের ফোন নম্বর, পেমেন্ট পদ্ধতির ধরন এবং অর্ডার রেফারেন্স নম্বর প্রক্রিয়া ও লগ করে।</li>
          <li><strong className="text-slate-800 dark:text-slate-200">ডিভাইস ও অ্যাপ মেটাডেটা (রিলে অ্যাপ):</strong> ডিভাইস মডেল, অ্যান্ড্রয়েড OS সংস্করণ, অ্যাপ সংস্করণ, কানেক্টিভিটি স্ট্যাটাস এবং শেষ দেখার টাইমস্ট্যাম্প সহ ডিভাইস-নির্দিষ্ট অপারেশনাল তথ্য।</li>
          <li><strong className="text-slate-800 dark:text-slate-200">অ্যাড-অন ব্যবহারের ডেটা:</strong> মার্চেন্ট কোনো অ্যাড-অন সেবা সক্রিয় করলে, আমরা সেই অ্যাড-অন ব্যবহার সংক্রান্ত ব্যবহারের মেট্রিক্স সংগ্রহ ও ধরে রাখি — সঠিক ব্যবহার-ভিত্তিক বিলিং, চালান তৈরি এবং বিরোধ সমাধানের উদ্দেশ্যে।</li>
          <li><strong className="text-slate-800 dark:text-slate-200">KYC ও ব্যবসা যাচাই দলিল:</strong> আমাদের KYC এবং ব্যবসা যাচাইকরণ নীতির অধীনে প্রয়োজন হলে, আমরা মার্চেন্ট কর্তৃক জমা দেওয়া ব্যবসায়িক পরিচয় দলিল সংগ্রহ, প্রক্রিয়া ও নিরাপদে সংরক্ষণ করি।</li>
          <li><strong className="text-slate-800 dark:text-slate-200">ব্যবহার ও লগ ডেটা:</strong> নিরাপত্তা পর্যবেক্ষণ, জালিয়াতি সনাক্তকরণ এবং সিস্টেম উন্নতির জন্য স্বয়ংক্রিয়ভাবে সংগৃহীত IP ঠিকানা, ব্রাউজারের ধরন, অপারেটিং সিস্টেম এবং সেশন টাইমস্ট্যাম্প।</li>
          <li><strong className="text-slate-800 dark:text-slate-200">যোগাযোগ:</strong> আপনার এবং Xelpay সাপোর্ট স্টাফের মধ্যে সাপোর্ট কথোপকথন, মতামত বার্তা এবং ইমেইল যোগাযোগের রেকর্ড।</li>
        </ul>
        <div className="mt-4">
          <InfoBox type="success">
            <strong className="block mb-1">আমরা যা কখনও সংগ্রহ করি না:</strong>
            Xelpay কখনোই আপনার ব্যাংক অ্যাকাউন্টের পাসওয়ার্ড, MFS অ্যাপ PIN কোড, OTP, NID/পাসপোর্ট নম্বর (KYC সম্মতির জন্য স্বেচ্ছায় জমা দেওয়া ব্যতীত), কাঁচা ক্রেডিট/ডেবিট কার্ড নম্বর বা CVV কোড রেকর্ড, সংরক্ষণ বা লগ করে না।
          </InfoBox>
        </div>
      </SectionBlock>
      <SectionBlock title="২–১২. বিস্তারিত বাংলা বিষয়বস্তু" icon={Scale} accent="green">
        <p>সম্পূর্ণ বাংলা গোপনীয়তা নীতি পড়তে ইংরেজি ভাষা নির্বাচন করুন অথবা আমাদের সাপোর্ট টিমের সাথে যোগাযোগ করুন। মূল বিষয়গুলো: ডেটা সংগ্রহের আইনগত ভিত্তি, ডেটা ব্যবহারের উদ্দেশ্য, কুকিজ নীতি, তৃতীয় পক্ষের সাথে ডেটা শেয়ারিং, ডেটা নিরাপত্তা, ইলেকট্রনিক যোগাযোগে সম্মতি, ডেটা সংরক্ষণ নীতি, আপনার অধিকার, শিশুদের গোপনীয়তা, আন্তর্জাতিক ডেটা স্থানান্তর এবং যোগাযোগ তথ্য।</p>
      </SectionBlock>
    </div>
  );
}

// ─── MAIN PAGE ────────────────────────────────────────────────────────────────
export default function PrivacyPolicyPage() {
  const [lang, setLang] = useState<Lang>('en');

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#0B1120] transition-colors duration-500 font-sans">
      <InfoHeader />

      <main className="py-10 px-4 md:px-6">
        <div className="max-w-5xl mx-auto">

          {/* Back link */}
          <Link href="/" className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 font-medium mb-8 transition-colors text-sm">
            <ArrowLeft size={16} /> Back to Home
          </Link>

          {/* Header Card — info/slug style */}
          <div className="bg-white dark:bg-[#111827] p-7 md:p-10 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 mb-6">
            <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4 mb-4">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-green-50 dark:bg-green-900/20 rounded-xl flex items-center justify-center shrink-0">
                  <ShieldCheck size={24} className="text-green-600 dark:text-green-400" />
                </div>
                <div>
                  <h1 className="text-2xl md:text-3xl font-bold text-slate-900 dark:text-white tracking-tight">
                    {lang === 'en' ? 'Privacy Policy' : 'গোপনীয়তা নীতি'}
                  </h1>
                  <div className="w-10 h-0.5 bg-green-600 rounded-full mt-2"></div>
                </div>
              </div>
              {/* Language toggle */}
              <div className="flex items-center gap-2 shrink-0">
                <Globe size={14} className="text-slate-400" />
                <div className="flex rounded-xl overflow-hidden border border-slate-200 dark:border-slate-700 text-xs font-black">
                  <button onClick={() => setLang('en')}
                    className={`px-3 py-1.5 transition-colors uppercase tracking-widest ${lang === 'en' ? 'bg-blue-600 text-white' : 'bg-white dark:bg-slate-800 text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700'}`}>
                    EN
                  </button>
                  <button onClick={() => setLang('bn')}
                    className={`px-3 py-1.5 transition-colors ${lang === 'bn' ? 'bg-blue-600 text-white' : 'bg-white dark:bg-slate-800 text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-700'}`}>
                    বাং
                  </button>
                </div>
              </div>
            </div>
            <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">
              {lang === 'en'
                ? 'Last Updated: April 01, 2026 · Effective Immediately · Compliant with Bangladesh Digital Security Act 2018, BFIU AML guidelines, and GDPR principles.'
                : 'সর্বশেষ আপডেট: ১ এপ্রিল, ২০২৬ · তাৎক্ষণিকভাবে কার্যকর'}
            </p>
          </div>

          {/* Content */}
          <div className="text-slate-600 dark:text-slate-400 font-medium leading-relaxed text-sm md:text-base">
            {lang === 'en' ? <EnglishContent /> : <BanglaContent />}
          </div>

          {/* Footer note */}
          
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-[#0f172a] text-slate-500 py-8 px-6 border-t border-slate-800 mt-10">
        <div className="max-w-5xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4 text-xs">
          <Link href="/" className="flex items-center gap-1">
            <span className="text-xl font-black text-blue-600 tracking-tighter">X</span>
            <span className="text-lg font-semibold text-white tracking-tight -ml-0.5">elPay</span>
          </Link>
          <div className="flex gap-5">
            <Link href="/info/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/info/terms" className="hover:text-white transition-colors">Terms</Link>
            <Link href="/info/about" className="hover:text-white transition-colors">About</Link>
          </div>
          <span className="opacity-40 uppercase tracking-widest text-[10px]">© {new Date().getFullYear()} XelPay · Xenverse IT · All Rights Reserved</span>
        </div>
      </footer>
    </div>
  );
}